### ISSUE TITLE
Support for ActiveStorage cacheing

### ISSUE THREAD

**Issue by coderberry** [wrstudios/reso_transport#4]
Hi all!

I hope our application on Heroku and their filesystem is ephemeral which negates the value of cacheing with this gem. I created a monkeypatch that I wanted to share with you all to make it so I can use ActiveStorage to cache instead.

Just to provide context, here's an example of what I would use to pass in as an argument to the `md_file` option:

```ruby
client = ResoTransport::Client.new({
  md_file: Mls.create(name: "ACME MLS", code: "acme").to_signed_global_id,
  endpoint: ENDPOINT
  authentication: {
    access_token: TOKEN
    token_type: "Bearer"
  }
})
```

and here's the monkey patch I have as an initializer:

```ruby
# Monkeypatch the ResoTransport gem. Currently, the gem requires that a file is used to store the cache,
# however Heroku uses an ephemeral filesystem [1] that negates the value of cacheing with this gem.
#
# This monkey patch will replace the file storage with ActiveStorage
#
# [1] https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

class Module
  def redefine_const(name, value)
    __send__(:remove_const, name) if const_defined?(name)
    const_set(name, value)
  end
end

class MetadataWithActiveRecordCache < ResoTransport::Metadata
  def get_data
    if client.md_file
      mls = GlobalID::Locator.locate_signed(client.md_file)
      if mls.metadata_cache.attached? && mls.metadata_cache.blob.byte_size > 0
        return mls.metadata_cache.blob.download
      else
        raw_md = raw # Note: `raw` is a method on the Metadata class
        if raw_md.length > 0
          mls.metadata_cache.attach(io: StringIO.new(raw_md), filename: "#{mls.code}_metadata.xml", content_type: "text/xml")
        end
      end
    end
    raw
  end
end

ResoTransport.redefine_const(:Metadata, MetadataWithActiveRecordCache)
```

**Comment by jondruse** [comment]
Very interesting.  I'm not sure if there's much benefit of storing the metadata somewhere other than a local file system.  The metadata is usually quite large, so storing it on S3 or something still requires you to download it, but S3 is potentially a lot faster than a normal mls feed.

**Comment by coderberry** [comment]
@jondruse I agree that there will be a delay in loading the cache. If you can think of another way that might be more suitable for speed, I'd love to learn from you!

**Comment by jondruse** [comment]
@coderberry I'm going to work on abstracting the caching mechanism to something that has a simple enough api that you could just inject a new class in the configuration and then it can be whatever you want it to be.

**Comment by jondruse** [comment]
@coderberry Check out that PR for how you might be able to create your own class to handle that caching.  I didn't want to add any more dependencies to this gem so this seemed like the best way.  Let me know what you think.

**Comment by coderberry** [comment]
@jondruse I just saw your message. The integration looks amazing! Thank you for making this happen.
